1) Load CMCdemo-20182-withreps.txt and CMCscript

2)
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOB_HISTORY;

3) SET pagesize 200

4) NONE

5) No answer needed

6) DESC LOCATIONS;

7)
SELECT  LOCATION_ID “City#”, CITY “City”, STATE_PROVINCE || ‘ IN THE ‘ || as “Province with Country Code”
FROM    LOCATIONS
WHERE   LOCATION_ID >= 1000 AND LOCATION_ID <= 1500;

8)
SELECT  DISTINCT DEPARTMENT_ID, JOB_ID
FROM    EMPLOYEES;
